### ISSUE TITLE
Support SVG

### ISSUE THREAD

**Issue by MaxGraey** [atom/image-view#102]

**Comment by 50Wliu** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by MaxGraey** [comment]
It just suggestion nothing more. You did a great job and I felt that for a complete happiness lacks only this format=) How it would look I leave to your discretion. It suggestion similar to this #61.
