### ISSUE TITLE
Should still have ability to view hexdump / byte code

### ISSUE THREAD

**Issue by sdrobs** [atom/image-view#16]
I often need to view the hex dump of an image for debugging purposes.

Sublime provides it when selecting an image:
![screenshot 2014-03-14 16 55 23](https://f.cloud.github.com/assets/3654110/2425805/11e6a4c6-abbb-11e3-8f88-3a2a72a300cc.png)

While it is certainly useful to be able to view the image directly within the editor, the inherent purpose of a text-editor is to, well, edit text. Perhaps a split screen for the image and its hex / byte code?

**Comment by platy11** [comment]
@1j01 @sdrobs Maybe we could add support to preview SVGs, and add a button that will just show the hex/byte/XML code?
// @izuzak

**Comment by damieng** [comment]
I think hex view is out of scope for this particular package and is better suited in a package of it's own such as the one recommended by @AbeEstrada

**Comment by spachner** [comment]
https://atom.io/packages/hex does not exist. Is it really removed or renamed?

regards

spachner

**Comment by fengerzh** [comment]
There is an alternative, but currently it cannot support files larger than 1M, it will freeze your Atom, be careful. https://atom.io/packages/hix

**Comment by gingerbeardman** [comment]
@fengerzh sadly hix has disappeared from github

any other recommendations?

my issue with the packages I've tried so far is that they all open the file as Text and require the user to choose an option to view as HEX. which becomes bothersome when you simply want to browse all binary files in a subdirectory.

Sublime simply views files with known binary extensions as hex rather than text.
